Fully Implement Nuxt UI to Replace Jinja Templates
AbandonTech/abandonauth pull request #120
Opened 2024-06-16 04:51 UTC by fisher60

## Summary

I have fully written the new UI into Nuxt. This new UI uses the abandon tech color theme and logo, but the overall design of the site is still up for discussion and design. This UI is by no means the final product and does not need to be a full representation of our final UI, but it is an improvement over the existing UI and offers the same functionality. 

Any part of this UI may change in the future. Some design discussion would be appreciated to ensure the UI is nice enough to be used in production, but larger redesigns and more nit-picky suggestions may not be helpful at this stage.

Home Page
![image](https://github.com/AbandonTech/abandonauth/assets/39353605/59461453-cbe2-4147-8614-fd4752e2b42f)

Creating a new application
![image](https://github.com/AbandonTech/abandonauth/assets/39353605/18d3dce8-1ab9-4547-a5c8-c16c3903bb76)

developer applications with multiple apps 
![image](https://github.com/AbandonTech/abandonauth/assets/39353605/07cf69e7-2e82-46f5-b03e-8048b6860334)

developer application detail page with callback URIs
![image](https://github.com/AbandonTech/abandonauth/assets/39353605/9b89cbe1-988c-4d7b-9dbb-908d2bd89923)

reset dev app token modal 
![image](https://github.com/AbandonTech/abandonauth/assets/39353605/da30825a-fb6d-4024-bfa4-54c65ffe454c)

Token has been reset modal
![image](https://github.com/AbandonTech/abandonauth/assets/39353605/9687bf58-c4cc-4ee0-b513-1040faa2c4b0)

Delete app modal (redirects to developer-applications page on successful delete)
![image](https://github.com/AbandonTech/abandonauth/assets/39353605/232a83be-b0e5-41af-95be-42c5d7cba34a)

New login page
![image](https://github.com/AbandonTech/abandonauth/assets/39353605/302bce45-1b13-44cb-82ff-728c80a369f7)

2024-06-16 04:53 UTC, fisher60 commented
This pull request is still a draft as it requires a lot of work on the build/deploy and dev environment to get this in a state where it can be used. The current changes destroy the existing, jinja template UI and therefore must be all-inclusive.

2024-06-16 14:56 UTC, GDWR requested changes
All my comments are suggestions, except one which states it.

Please resolve them as you desire. Its looking really really good.

2024-06-16 14:56 UTC, GDWR commented on site/pages/developer-applications/index.vue
> +            <button class="text-left">{{ app.id }}</button>
I'd suggest not showing this here, it can be displayed when you click on it.

2024-06-16 14:56 UTC, GDWR commented on site/pages/developer-applications/[id].vue
> +            <input type="text" class="grow bg-inherit" placeholder="New Callback Uri" v-model="newCallbackUriName" @keydown.enter="addCallbackUri(newCallbackUriName)"/>
```suggestion
        <h2 class="mt-10 text-lg  ">Add Callback URI</h2>
        <div class="pt-2 w-96">
          <label class="input input-bordered input-ghost flex items-center bg-base-200">
            <input type="text" class="grow bg-inherit" placeholder="New Callback URI" v-model="newCallbackUriName" @keydown.enter="addCallbackUri(newCallbackUriName)"/>
```

2024-06-16 14:56 UTC, GDWR commented on site/pages/developer-applications/[id].vue
> +      <h2 class="text-2xl mt-10">Callback Uris</h2>
```suggestion
      <h2 class="text-2xl mt-10">Callback URIs</h2>
```

2024-06-16 14:56 UTC, GDWR commented on site/pages/developer-applications/[id].vue
> +      <p class="text-lg"><span>Application ID: </span><span>{{ application?.id }}</span></p>
Would suggest making this less pronounced colour (shade of grey).

Also a copy button with icon https://fontawesome.com/icons/copy?f=classic&s=solid would be awesome, can be a few places for this to be useful for example the Token.

2024-06-16 14:56 UTC, GDWR commented on site/pages/developer-applications/[id].vue
> +        <button class="btn btn-error w-28" @click="closeResetTokenAppModal">No</button>
Shouldn't the destructive action be red?

2024-06-16 14:56 UTC, GDWR commented on site/pages/developer-applications/[id].vue
> +      <p class="text-lg mt-2"><span>Token: </span><CopyString class="text-orange-500" :content="newToken"/></p>
Would suggest monospace when viewing tokens.

2024-06-16 14:56 UTC, GDWR commented on site/pages/developer-applications/[id].vue
> +    <div class="mx-auto my-10">
Some pages are left aligned (one seems left aligned and fill) some are center aligned. I'd suggest using one, and from the screenshots the left aligned looks better imo.

2024-06-16 14:56 UTC, GDWR commented on site/components/CopyString.vue
> +    content: String | undefined,
There is a shorthand for this type (and allows for the value to not exist in the obj).
```suggestion
    content?: string,
```

2024-06-16 14:56 UTC, GDWR commented on site/components/CopyString.vue
> +  let copyContent = props.content !== undefined ? props.content : "Id failed to load"
```suggestion
  let copyContent = props.content ?? "Id failed to load"
```

2024-06-16 14:56 UTC, GDWR commented on site/components/LoginButton.vue
> +})
```suggestion
defineProps<{
    title: string,
    redirectUrl: string,
    svgPathData: string,
    svgViewbox: string,
    bgColorClass: string,
}>();
```

2024-06-16 14:56 UTC, GDWR commented on site/components/NavLinkButton.vue
> +    title: String,
This is the only non-suggestion, as it infects the typesystem.

```suggestion
    title: string,
```
Avoid `String`, use `string`

[Some documentation for this, as its just one of those things](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#number-string-boolean-symbol-and-object)

2024-06-16 14:56 UTC, GDWR commented on site/components/NavLinkButton.vue
> +    title: String,
Avoid `String`, use `string`

[Some documentation for this, as its just one of those things](https://www.typescriptlang.org/docs/handbook/declaration-files/do-s-and-don-ts.html#number-string-boolean-symbol-and-object)

2024-06-16 14:56 UTC, GDWR commented on site/pages/developer-applications/[id].vue
> +    await submitNewCallbackUris(newUris)
```suggestion
    await submitNewCallbackUris([...application.value.callback_uris, uri]);
```

2024-06-16 14:56 UTC, GDWR commented on site/pages/login.vue
> +const githubSvgPath = "M13.2101 30.9016C13.2101 31.0561 13.0339 31.1797 12.8117 31.1797C12.5589 31.2028 12.3827 31.0792 12.3827 30.9016C12.3827 30.7471 12.5589 30.6235 12.781 30.6235C13.0109 30.6003
:thinking: can we use a `.svg` file?

2024-06-16 17:23 UTC, fisher60 commented on site/pages/developer-applications/index.vue
> +            <button class="text-left">{{ app.id }}</button>
Is this referring specifically to the application ID?

I believe a common use case of this page will be only having an existing application ID on a project and attempting to find it from this menu, so I believe it will be important to display the app IDs here.

2024-06-16 23:02 UTC, fisher60 commented on site/pages/developer-applications/[id].vue
> +        <button class="btn btn-error w-28" @click="closeResetTokenAppModal">No</button>
I can't quite decide on these. I really hate having the reject/no button as green and the accept button as red, it seems counter intuitive to me and more likely to cause a mistake. This way, the reject action is still red, but the accept action is still a warning color, rather than green (which could indicate a safe action).

2024-06-16 23:10 UTC, GDWR commented on site/pages/developer-applications/[id].vue
> +        <button class="btn btn-error w-28" @click="closeResetTokenAppModal">No</button>
I'd do `Delete` in red and `Cancel` in grey.

2024-06-16 23:14 UTC, fisher60 commented on site/pages/login.vue
> +const githubSvgPath = "M13.2101 30.9016C13.2101 31.0561 13.0339 31.1797 12.8117 31.1797C12.5589 31.2028 12.3827 31.0792 12.3827 30.9016C12.3827 30.7471 12.5589 30.6235 12.781 30.6235C13.0109 30.6003
I think that is a good idea, I have no idea how to do that, so we can change that at a later date/source proper SVGs instead of depending on inline SVG definitions.

2024-06-18 04:41 UTC, fisher60 commented
After many hours of pain, this should be ready for review. pre-commit is not working locally, so linting is a pain. This will need to be fixed. We can dedicate a new PR to this if the problem is not simple.

2024-06-18 04:42 UTC, fisher60 commented
Closes #81 #82

2024-06-18 18:25 UTC, GDWR approved these changes

2024-06-18 18:43 UTC, merged