Create user method
AbandonTech/abandonauth pull request #83
Opened 2024-04-15 20:10 UTC by Lopkop

2024-04-15 20:12 UTC, Lopkop commented
I'm not quite sure if prisma is compatible with pydanticv2, because I get this error: ImportError: cannot import name 'ModelField' from 'pydantic.fields'

2024-04-16 16:00 UTC, fisher60 commented
> I'm not quite sure if prisma is compatible with pydanticv2, because I get this error: ImportError: cannot import name 'ModelField' from 'pydantic.fields'

Hello, sorry about this. I updated to Pydantic V2 and Prisma seems to generate the client based on your current version of Pydantic.

To fix this you will need to run `python -m prisma_cleanup`, then regenerate your Prisma client with `prisma generate`, this will create a new Prisma client using Pydantic V2

2024-04-16 17:36 UTC, fisher60 requested changes
Thank you for your help on this! Overall, it looks pretty good, I have pointed out a few issues and requests for changes as well as some design changes that may deviate from the initial design.

I may have led you a bit astray with earlier descriptions, so I apologize for that as we would like to see some design changes here that I have outlined as part of the review. 

I hope I have not "moved the goalposts" too much. Overall this initial implementation looks good and I think the changes I specified here should make this ready to rollout.

2024-04-16 17:36 UTC, fisher60 commented on abandonauth/routers/test_router.py
> +    return {'user_id': test_user.id}
This can result in an "orphaned" `User`, we should be creating the User along with the test user, identical to how we have done it for our other login methods. https://github.com/AbandonTech/abandonauth/blob/main/abandonauth/routers/discord.py#L53-L62

2024-04-16 17:36 UTC, fisher60 commented on abandonauth/routers/test_router.py
> +    })
We should not be passing an ID to the User directly. We can still allow prisma to generate the user's UUID.

We should treat the `TestUser` as an authentication method, similar to a `DiscordAccount`. The TestUser and User can have different IDs. Perhaps a compound ID between `User` and `TestUser`, the `TestUser` could also just use a simple integer ID as TestUsers only need to be unique for each User-TestUser relationiship.

2024-04-16 17:36 UTC, fisher60 commented on abandonauth/settings.py
> +    DEBUG: str
I would prefer if we made this field a boolean. I would like if it needed to explicitly be set as `false` in production. Using a string can result in undesirable behavior. I.e right now `DEBUG` is required. Setting `DEBUG=False` in the `.env` will actually result in `DEBUG` being evaluated as truthy and therefore require production to behave as if `DEBUG == True`.

2024-04-16 17:36 UTC, fisher60 commented on prisma/schema.prisma
> +  TestUser               TestUser[]
The current implementation would not allow for a single user to own multiple TestUsers, so this schema is innacurate. Instead we should treat a `TestUser` similar to a `DiscordAccount`, i.e each user can have one `TestUser` and it can be null
`TestUser?`

2024-04-16 17:36 UTC, fisher60 commented on prisma/schema.prisma
> +  TestUser               TestUser[]
This field should be `snake_case` by our project's conventions.

2024-04-16 17:36 UTC, fisher60 commented on prisma/schema.prisma
> +}
We should revise this model to behave similar to a `DiscordAccount`, rather than an independent user. The `TestUser` should behave as a login method, the `User` model should contain the actual user data. The username will belong to the `User` model, the `TestUser` should not utilize a `refresh_token`. Technically this app treats `refresh_token` and `password` identically and the terms can be used interchangeably  for AbandonAuth.

We should only require these fields on the test user:
```
  id      BigInt @id
  password String
  user    User   @relation(fields: [user_id], references: [id], onDelete: Cascade)
  user_id String @unique @db.Uuid
  ```

2024-04-16 17:36 UTC, fisher60 commented on prisma/schema.prisma
> +model TestUser {
This naming is a bit confusing given the other review comments I have for changes. We should rename this to something like `PasswordAccount` to be consistent with our other login models.

2024-04-16 17:36 UTC, fisher60 commented on abandonauth/routers/test_router.py
> +from abandonauth.settings import settings
The term `test_router` could be a bit misleading.

We should rename this router/module to more accurately describe what it does. Perhaps `password_login.py` or `debug_login.py` (based on my other review comments regarding schema naming).

2024-04-23 04:12 UTC, fisher60 requested changes
This is looking really good, just a few minor changes I would like to see implemented before accepting.

2024-04-23 04:12 UTC, fisher60 commented on abandonauth/routers/password_login.py
> +        return {'message': 'Invalid password'}
We should raise an exception here. We can also duplicate the more secure logic we already have for developer applications. (Though the user and password checks are combined to prevent brute-forcing/data-mining and are admittedly not really necessary on this dev endpoint)

```suggestion
  if password_account is None or not verify_data(user_data.password, password_account.password):
        raise HTTPException(
            status_code=HTTP_401_UNAUTHORIZED,
            detail="Invalid username or password",
        )
```

2024-04-23 04:12 UTC, fisher60 commented on abandonauth/routers/password_login.py
> +    return {'access_token': access_token}
We can reuse our JWT DTO for this response https://github.com/AbandonTech/abandonauth/blob/main/abandonauth/routers/developer_application.py#L80

2024-04-23 18:45 UTC, Lopkop commented
@fisher60 Thanks for review

2024-04-25 18:10 UTC, fisher60 approved these changes
LGTM. Thank you so much for your help on this!

I see some cleanup we can do on the response/return types on endpoints, but I would be happy to merge this and clean that up in a later PR after we get a chance to play around with some of this logic.

Would like to see @GDWR thoughts on this PR as well before merging.

2024-04-26 09:51 UTC, GDWR approved these changes
Looking good, added two comments for things that should be fine but might be a little in-optimal or redundant.

2024-04-26 09:51 UTC, GDWR commented on prisma/schema.prisma
> +  @@unique([id, username])
We wouldn't want to make this a composite key, we should be unique over `id` alone.
The already existing [`@id`](https://www.prisma.io/docs/orm/prisma-schema/data-model/models#defining-an-id-field) does this for us.

Not sure how `@id` and `@@unique` play together, but its easier to just stick with `@id` as it will make a id-username pair unique intrinsically.

2024-04-26 09:51 UTC, GDWR commented on prisma/migrations/20240418110549_refactor_password_account/migration.sql
> +DROP TABLE "TestUser";
Kinda a nit pick here, as this PR as been through a significant change in the database structure. It might be best to (remove and then) recreate all the migrations so we are not creating and removing a table within two migrations for no reason.

I'll be resolving this as it doesn't actually matter, just a cleanliness factor so worth noting.

2024-04-29 10:27 UTC, Lopkop commented on prisma/schema.prisma
> +  @@unique([id, username])
> its easier to just stick with @id as it will make a id-username pair unique intrinsically.

good point, thanks for review!

2024-04-30 03:02 UTC, merged

2024-04-30 03:05 UTC, fisher60 commented
Thank you! Before merging, I added a quick fix for the settings import in the routers `__init__`, and a small tweak to just add a tag to the password account router.