Add name to DeveloperApplication
AbandonTech/abandonauth pull request #92
Opened 2024-05-06 16:13 UTC by Lopkop

Hello there! This small PR closes

1. Add name to DevApplication schema
2. Add name field in the endpoints
3. Refactor html file to display the name and id of application

2024-05-30 09:29 UTC, GDWR approved these changes
Looks good, just one small thing.

2024-05-30 09:29 UTC, GDWR commented on abandonauth/routers/ui.py
> +            "dev_apps": [(x["name"], x["id"]) for x in dev_apps],
I wonder if we could use a dictionary structure here, would make the HTML template usage clearer too.

```suggestion
            "dev_apps": [{"name": x["name"], "id": x["id"])} for x in dev_apps],
```

Or even just
```suggestion
            "dev_apps": [x for x in dev_apps],
```
although I prefer the first as we explicitly say what is available to the template.

2024-05-30 18:43 UTC, Lopkop commented on abandonauth/routers/ui.py
> +            "dev_apps": [(x["name"], x["id"]) for x in dev_apps],
Thanks for review!

2024-05-31 02:56 UTC, fisher60 requested changes
This looks really good. 

We need to update the template `create_developer_app.html` to use the new `name` field. Currently if you try to create a new developer app with the UI it will fail with an HTTP 422 error since the `name` is required now in the body.

2024-06-06 05:48 UTC, fisher60 commented
I just pushed the changes needed to use the UI for creating a developer app with a name. I also cleaned some things up.

I threw away some changes that appear to be from auto-formatting from another PR as they greatly complicated rebasing.

In hindsight, I should not have rebased and force-pushed since the history is kinda goofy and makes it look like I was more involved than I was. Rest assured; all credit to @Lopkop for implementing this feature.

2024-06-07 22:03 UTC, merged